# -*- coding: utf-8 -*-
"""business-it-workshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZJBBsx9kFT9_zQWkmhlaO23jS3gbw7Ib
"""

from datetime import datetime
import requests
import pandas as pd
from bs4 import BeautifulSoup

url = "https://webscraper.io/test-sites/e-commerce/allinone/computers/laptops"


response = requests.get(url, timeout=20)
response.encoding = "utf-8"                            # ensure £ signs display correctly
soup = BeautifulSoup(response.text, "html.parser")
scrape_time = datetime.now().isoformat()

rows = []
scrape_time = datetime.now().isoformat()
for laptop in soup.select(".card"):
    title = laptop.select_one(".title")["title"]
    manufacturer=laptop.select_one(".title")["title"].split(" ")[0]
    price_text=laptop.select_one("span").getText(strip=True)
    rating_element = laptop.select_one("p[data-rating]")
    rating = rating_element.get("data-rating") if rating_element else "0"
  # new field

    # The rating is stored as a CSS class, e.g. class="star-rating Three"
    # We grab the <p> element, then read its class list to find the rating word

    rows.append({
        "title": title,
        "manufacturer":manufacturer,
        "price": price_text,
        "rating": rating,
        "scraped_at": scrape_time
         # new field
    })

df = pd.DataFrame(rows)
df

# Check what your DataFrame looks like right now


df["price"] = (
    df["price"]
      .str.replace(r"[^0-9.]", "", regex=True)  # keep only digits and dots
      .astype(float)
)

df

df["rating"] = (
    df["rating"]
      .str.replace(r"[^0-9.]", "", regex=True)  # keep only digits and dots
      .astype(float)
)

df

df["manufacturer"] = (
    df["manufacturer"] # keep only digits and dots
      .astype(str)
)

df


# Fill missing ratings with "Unknown" so they still appear in charts
df["rating"] = df["rating"].fillna("Unknown")

df = df.rename(columns={
    "title": "name",
})
  # verify the renamed columns
df

# Final check


df.to_csv("verify_output.csv", index=False)
print(f"Rows: {len(df)}  |  Columns: {list(df.columns)}")
df
     # first few rows

# !pip -q install supabase

# from supabase import create_clientd
# from datetime import datetime

# SUPABASE_URL = "https://nbbzrpdcblcqsahglqsd.supabase.co"   # your Project URL
# SUPABASE_KEY = "sb_publishable_TfQAao_Glu8QUwm57qi3OQ_hJsChQPG"              # your anon/public key

# supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# scrape_time = datetime.now().isoformat()

# rows = []
# for _, row in df.iterrows():
#     rows.append({
#         "name":        str(row.get("name", "")),
#         "manufacturer":    str(row.get("manufacturer", "")),
#         "price":  float(row.get("price", 0)),
#         "rating": float(row.get("rating", 0)),
#     })

# result = supabase.table("laptops").insert(rows).execute()
# print(f"✅ Inserted {len(rows)} rows into Supabase")


import os
from supabase import create_client
from datetime import datetime

import os

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
scrape_time = datetime.now().isoformat()
filename = "my_dataset.csv"

if os.path.exists(filename):
    # File already exists → append without writing headers again
    df.to_csv(filename, mode="a", header=False, index=False)
else:
    # First run → create file with headers
    df.to_csv(filename, index=False)

print(f"Appended {len(df)} rows to local CSV — total file now has historical data")
rows = []
for _, row in df.iterrows():
    rows.append({
        "name": str(row.get("name", "")),
        "manufacturer": str(row.get("manufacturer", "")),
        "price": float(row.get("price", 0)),
        "rating": float(row.get("rating", 0)),
    })

result = supabase.table("laptops").insert(rows).execute()
print(f"✅ Inserted {len(rows)} rows into Supabase")